### ISSUE TITLE
Support printer

### ISSUE THREAD

**Issue by evan361425** [evan361425/flutter-pos-system#210]
### What do you expect this feature to look like?

- Bluetooth connect
- Linked by USB

### Any additional comments?

- https://github.com/tcd93/flutter-pos

### Before opening a new issue

- [X] I have checked other [issues](https://github.com/evan361425/flutter-pos-system/issues)

**Comment by imadegunawinangun** [comment]
bluetooth:
    git:
      url: https://github.com/evan361425/flutter-pos-packages
      ref: master
      path: packages/bluetooth
      
      where can i get this packages?

**Comment by evan361425** [comment]
This is a private repo because we are concerned that some vendors might not want their code to be decompiled, so it has not been made public.

**Comment by evan361425** [comment]
I've update the [document](https://evan361425.github.io/flutter-pos-system/maintenance/development/) for developing.

You must change it to public mocked package [flutter-pos-packages-mock](https://github.com/evan361425/flutter-pos-packages-mock):

```bash
sed -i.bk 's/flutter-pos-packages$/flutter-pos-packages-mock/' pubspec.yaml
rm -f pubspec.yaml.bk
```

**Comment by evan361425** [comment]
Close this issue as we are supported now. Any new printers wanted to support can open a new issue.
