### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by hasanelfalakiy** [evan361425/flutter-pos-system#213]
why this app not available in my country?
from google play

**Comment by evan361425** [comment]
Which country are you in now?

**Comment by hasanelfalakiy** [comment]
> Which country are you in now?

Indonesia

**Comment by evan361425** [comment]
I will open it globally after floating currency has done but I'll open to Indonesia in next release for you👍

**Comment by hasanelfalakiy** [comment]
> I will open it globally after floating currency has done but I'll open to Indonesia in next release for you👍

oh okay 👍

**Comment by evan361425** [comment]
done
